### ISSUE TITLE
undefine challenge

### ISSUE THREAD

**Issue by Rohit-jagdale** [MasterKale/SimpleWebAuthn-homepage#68]
```
profile.html?userId=user_1734505294184:66 Registration Error: TypeError: Cannot read properties of undefined (reading 'challenge')
    at e.startRegistration (index.umd.min.js:2:4892)
    at HTMLButtonElement.<anonymous> (profile.html?userId=user_1734505294184:63:70)
``` 
    
I am getting this error when I setup from backend server and when I tried to setup from frontend using js script this error cames

**Comment by bishwajitcadhikary** [comment]
Pass your public key credential creation options data like this. Maybe it works.

```javascript
const submit = async () => {
    try {
        const options = await axios.get(route('api.v1.passkeys.register'));
        const credential = await startRegistration({
            optionsJSON: options.data,
            useAutoRegister: false, // optional, defaults to false
        });

        console.log(credential);
    } catch (error) {
        console.error(error);
    }
};
```

**Comment by Rohit-jagdale** [comment]
> Pass your public key credential creation options data like this. Maybe it works.
> 
> ```js
> const submit = async () => {
>     try {
>         const options = await axios.get(route('api.v1.passkeys.register'));
>         const credential = await startRegistration({
>             optionsJSON: options.data,
>             useAutoRegister: false, // optional, defaults to false
>         });
> 
>         console.log(credential);
>     } catch (error) {
>         console.error(error);
>     }
> };
> ```

I tried this but again get error 
Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')
    at base64URLStringToBuffer (http://localhost:3000/main.7baa432fc88123c2229b.hot-update.js:12519:34)
    at startRegistration (http://localhost:3000/main.7baa432fc88123c2229b.hot-update.js:13282:103)
    at Object.collectData [as onSubmit] (http://localhost:3000/main.2e213d519c1e5585e334.hot-update.js:116:110)

**Comment by Rohit-jagdale** [comment]
> Pass your public key credential creation options data like this. Maybe it works.
> 
> ```js
> const submit = async () => {
>     try {
>         const options = await axios.get(route('api.v1.passkeys.register'));
>         const credential = await startRegistration({
>             optionsJSON: options.data,
>             useAutoRegister: false, // optional, defaults to false
>         });
> 
>         console.log(credential);
>     } catch (error) {
>         console.error(error);
>     }
> };
> ```
thanks alot I got the issue it was in server site generateRegistrationOptions the userId is not given

**Comment by bishwajitcadhikary** [comment]
I've updated the sample code.

**Comment by MasterKale** [comment]
```
TypeError: Cannot read properties of undefined (reading 'challenge')
```

This sounds like options were being passed in as `startRegistration(options)` instead of `startRegistration({ optionsJSON: options })`, to account for this breaking API change in v11.0.0:

https://github.com/MasterKale/SimpleWebAuthn/releases/tag/v11.0.0

> thanks alot I got the issue it was in server site generateRegistrationOptions the userId is not given

It _sounds_ like this issue has been resolved, so I'm going to close it. Feel free to reopen if your original issue isn't actually resolved.
